q9:
	gcc -c num_caracs.c
	gcc -c Questão9.c
	gcc -o cont_caracs num_caracs.o Questão9.o

q11:
	gcc -c num_caracs.c
	gcc -c Questão11.c
	gcc -o cont_caracs2 num_caracs.o Questão11.o

clean:
	rm -f *.o cont_caracs cont_caracs2